name: Test install on Kali Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-install:
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling:latest  # Use the correct tag

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update packages and install dependencies
      run: |
        apt-get update
        apt-get install -y ca-certificates

    # Running installer.sh
    - name: Run installer script
      run: |
        ./installer.sh